name: Revisar HTML y CSS

on:
  push:
    paths:
      - '**.html'
      - '**.css'
  pull_request:
    paths:
      - '**.html'
      - '**.css'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar htmlhint y stylelint
        run: |
          npm install -g htmlhint stylelint

      - name: Revisar archivos HTML
        run: htmlhint "**/*.html"

      - name: Revisar archivos CSS
        run: stylelint "**/*.css" || true
